#include "stdafx.h"
#include "Mountain.h"
#include "Climber.h"
#include "Club.h"
#include "ClubStats.h"

ClubStats::ClubStats() {};

/*void ClubStats::WelcomeMessage()
{
	//ascii art done by Joan Stark (taken from https://www.ascii-code.com/)
	cout << "#################################################################################" << endl;
	cout << "			Welcome to Misty Mountains Club!" << endl;
	cout << "	        _    .  ,   .           ." << endl;
	cout << "	    *  / \\_ *  / \\_      _  *        *   /\\'__        *" << endl;
	cout << "	      /    \\  /    \\,   ((        .    _/  /  \\  *'." << endl;
	cout << "	 .   /\\/\\  /\\/ :' __ \\_  `          _^/  ^/    `--." << endl;
	cout << "	    /    \\/  \\  _/  \\-'\\      *    /.' ^_   \\_   .'\\  *" << endl;
	cout << "	  /\\  .-   `. \\/     \\ /==~=-=~=-=-;.  _/ \\ -. `_/   \\ *. " << endl;
	cout << "	 /  `-.__ ^   / .-'.--\\ =-=~_=-=~=^/  _ `--./ .-'  `-" << endl;
	//ascii text generated by http://patorjk.com/software/taag/#p=display&f=Slant&t=Misty%20Mountains
	cout << "    __  ____      __           __  ___                  __        _           " << endl;
	cout << "   /  |/  (_)____/ /___  __   /  |/  /___  __  ______  / /_____ _(_)___  _____" << endl;
	cout << "  / /|_/ / / ___/ __/ / / /  / /|_/ / __ \\/ / / / __ \\/ __/ __ `/ / __ \\/ ___/" << endl;
	cout << " / /  / / (__  ) /_/ /_/ /  / /  / / /_/ / /_/ / / / / /_/ /_/ / / / / (__  ) " << endl;
	cout << "/_/  /_/_/____/\\__/\\__, /  /_/  /_/\\____/\\__,_/_/ /_/\\__/\\__,_/_/_/ /_/____/  " << endl;
	cout << "                  /____/                                                      " << endl;
	cout << "#################################################################################" << endl;

} */

void ClubStats::DisplayMenu()
{
	cout << "			   ### MAIN MENU ###" << endl;
	cout << "What would you like to do? " << endl;
	cout << "0 --> Enter main menu [you are currently here]" << endl;
	cout << "1 --> Add climber" << endl;
	cout << "2 --> Add a mountain climbed" << endl;
	cout << "3 --> Display club statistics [will open a sub-menu with option]" << endl;
}

void ClubStats::DisplayStatisticsSubMenu()
{
	cout << "		### Statistics Sub-Menu ###" << endl;
	cout << "You're in statistics sub-menu. Below are options to chose from:" << endl;
	cout << "0--> Go back to main menu" << endl;
	cout << "1--> Display climber with recorded highest average climbed" << endl;
	cout << "2--> Display highest mountain climbed by a club member" << endl;
	cout << "3--> Display all mountains recorded with a height greater than a given level" << endl;
}

void ClubStats::AskMenuOption()
{
	cout << "Choose an option (0/1/2/3): ";
	int userInput;
	cin >> userInput;
	while (userInput != 1 && userInput != 2 && userInput != 3 && userInput != 0)
	{
		cout << "\nThat's not a valid option. Valid options are: 0, 1, 2, 3" << endl;
		cin >> userInput;
	}
	userOptionChoice = userInput;
}

void ClubStats::DisplayAddClimberMenu()
{
	cout << "\n		### Add climber sub-menu##" << endl;
	cout << "You're now in the add climber menu. Adding a climber: " << endl;
	
}

char ClubStats::AskYesNo(string question)
{
	char answer;
	do {
		cout << question << "(y/n): ";
		cin >> answer;
	} while (answer != 'y' && answer != 'n');

	return answer;
}